apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-api
  template:
    metadata:
      labels:
        app: dns-api
    spec:
      containers:
        - name: dns-api
          image: "{{ .Values.dnsAPI.image }}"
          ports:
            - containerPort: {{ .Values.dnsAPI.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: dns-api
spec:
  selector:
    app: dns-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: {{ .Values.dnsAPI.port }}
